repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe, --quiet]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-typing-imports==1.9.0
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=.:src']
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
        args: [--min-py3-version=3.4]
